routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\Admin\Controller as AdminController;
use App\Http\Controllers\Admin\UnitController as AdminUnitController;
use App\Http\Controllers\Admin\ProgramController as AdminProgramController;
use App\Http\Controllers\Admin\IndicatorController as AdminIndicatorController;
use App\Http\Controllers\Admin\StructureController as AdminStructureController;
use App\Http\Controllers\Collectors\DataController as CollectorsDataController;
use App\Http\Controllers\Collectors\RecordController as CollectorsRecordController;
use App\Http\Controllers\Collectors\ProgramController as CollectorsProgramController;
use App\Http\Controllers\Admin\StructureTypeController as AdminStructureTypeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'revalidate_back_history'], function () {

    Route::group(['as' => 'auth.', 'prefix' => 'auth'], function () {

        Route::get('/', [LoginController::class, 'create'])->name('login');
        Route::get('/logout', [LogoutController::class, 'logout'])->name('logout');



        Route::group(['middleware' => ['costum_guest']], function () {
            Route::post('/', [LoginController::class, 'store'])->name('login.store');


            Route::get('/forgot-password', function () {
                return view('modules.shared.auth.login');
            });

            Route::get('/reset-password', function () {
                return view('modules.shared.auth.login');
            });
        });
    });


    Route::get('/', [HomeController::class, 'default'])->name('home.default');

    Route::group(['middleware' => 'administrator_checker', 'prefix' => 'admin', 'as' => 'admin.'], function () {
        Route::get('/', [AdminController::class, 'index'])->name('index');

        Route::resource('structures', AdminStructureController::class);
        Route::group(['prefix' => 'structures', 'as' => 'structures.'], function () {
            Route::post('/{structure}/programs', [AdminStructureController::class, 'programs_add'])->name('programs.add');
            Route::delete('/{structure}/programs', [AdminStructureController::class, 'programs_remove'])->name('programs.remove');
        });

        Route::resource('structure-types', AdminStructureTypeController::class);
        Route::resource('units', AdminUnitController::class);
        Route::resource('indicators', AdminIndicatorController::class);

        Route::resource('programs', AdminProgramController::class);
        Route::group(['prefix' => 'programs', 'as' => 'programs.'], function () {
            Route::post('/{program}/structures', [AdminProgramController::class, 'members_add'])->name('members.add');
            Route::delete('/{program}/structures', [AdminProgramController::class, 'members_remove'])->name('members.remove');
        });
    });


    Route::group(['middleware' => 'collector_checker', 'prefix' => 'pf', 'as' => 'pf.'], function () {
        Route::get('/', [CollectorsProgramController::class, 'index'])->name('collectors.index');


        Route::group(['prefix' => '/{program}', 'as' => 'programs.'], function () {
            Route::resource('data', CollectorsDataController::class)->except(['show']);

            Route::get('/data/with-values', [CollectorsDataController::class, 'index_with_values'])->name('data.index.with.values');


            Route::group(['prefix' => '/data/{data}', 'as' => 'data.'], function () {
                Route::resource('records', CollectorsRecordController::class)->only(['index', 'create', 'store']);
            });
        });
    });
});

resources/views/shared/menu/layout/default-footer.blade.php
<!-- Footer -->
<div class="legal">
    <div class="copyright">
        &copy; 2016 - 2017 <a href="javascript:void(0);">AdminBSB - Material Design</a>.
    </div>
    <div class="version">
        <b>Version: </b> 1.0.5
    </div>
</div>
<!-- #Footer -->

resources/views/shared/menu/layout/default-menu.blade.php
<!-- Menu -->
<div class="menu">
    <ul class="list">
        <li class="header">NAVIGATION</li>
        <li class="{{ $activa == 'home' || $activa == '' ? 'active' : '' }}">
            <a href="{{ route('admin.index') }}">
                <i class="material-icons">home</i>
                <span>Accueil</span>
            </a>
        </li>

        <li class="{{ $activa == 'structures' || $activa == 'structure-types' ? 'active' : '' }}">
            <a href="javascript:void(0);" class="menu-toggle">
                <i class="material-icons">widgets</i>
                <span>Structures et types</span>
            </a>
            <ul class="ml-menu">
                <li class=" {{ $activa == 'structures' ? 'active' : '' }}">
                    <a href="{{ route('admin.structures.index') }}">
                        @if ($activa != 'structures')
                            <i class="material-icons">business</i>
                        @endif
                        <span>Structures</span>
                    </a>
                </li>
                <li class=" {{ $activa == 'structure-types' ? 'active' : '' }}">
                    <a href="{{ route('admin.structure-types.index') }}">
                        @if ($activa != 'structure-types')
                            <i class="material-icons">title</i>
                        @endif
                        <span>Types de structure</span>
                    </a>
                </li>
            </ul>
        </li>

        <li class="{{ $activa == 'programs' ? 'active' : '' }}">
            <a href="{{ route('admin.programs.index') }}">
                <i class="material-icons">chrome_reader_mode</i>
                <span>Programmes</span>
            </a>
        </li>

        <li class="{{ $activa == 'units' || $activa == 'indicators' || $activa == 'data' ? 'active' : '' }}">
            <a href="javascript:void(0);" class="menu-toggle">
                <i class="material-icons">graphic_eq</i>
                <span>Statistique</span>
            </a>
            <ul class="ml-menu">
                <li class="{{ $activa == 'units' ? 'active' : '' }}">
                    <a href="{{ route('admin.units.index') }}">
                        @if ($activa != 'units')
                            <i class="material-icons">format_underlined</i>
                        @endif
                        <span>Unités</span>
                    </a>
                </li>


                <li class=" {{ $activa == 'indicators' ? 'active' : '' }}">
                    <a href="{{ route('admin.indicators.index') }}">
                        @if ($activa != 'indicators')
                            <i class="material-icons">data_usage</i>
                        @endif
                        <span>Indicateurs</span>
                    </a>
                </li>

                <li class=" {{ $activa == 'data' ? 'active' : '' }}">
                    <a href="#">
                        @if ($activa != 'data')
                            <i class="material-icons">grain</i>
                        @endif
                        <span>Données</span>
                    </a>
                </li>
            </ul>
        </li>

        <li>
            <a href="pages/changelogs.html">
                <i class="material-icons">help</i>
                <span>Documentation</span>
            </a>
        </li>
    </ul>
</div>
<!-- #Menu -->

resources/views/shared/menu/layout/default-user-info.blade.php
<!-- User Info -->
<div class="user-info">
    <div class="image">
        <img src="{{ asset('images/only-logo-wf.png') }}" width="48" height="48" alt="User" />
    </div>
    <div class="info-container">
        <div class="name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ auth()->user()->structure->name }}</div>
        <div class="email"><span class="badge bg-blue">{{ auth()->user()->username }}</span></div>
        <div class="user-helper-dropdown">
            <a href="{{ route('auth.logout') }}"
                class="btn bg-red btn-circle waves-effect waves-green waves-circle waves-float pull-right"
                style="margin-bottom: 10px;">
                <i class="material-icons">input</i>
            </a>
        </div>
    </div>
</div>
<!-- #User Info -->