routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\Admin\Controller as AdminController;
use App\Http\Controllers\Admin\UnitController as AdminUnitController;
use App\Http\Controllers\Admin\ProgramController as AdminProgramController;
use App\Http\Controllers\Admin\IndicatorController as AdminIndicatorController;
use App\Http\Controllers\Admin\StructureController as AdminStructureController;
use App\Http\Controllers\Collectors\DataController as CollectorsDataController;
use App\Http\Controllers\Collectors\RecordController as CollectorsRecordController;
use App\Http\Controllers\Collectors\ProgramController as CollectorsProgramController;
use App\Http\Controllers\Admin\StructureTypeController as AdminStructureTypeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'revalidate_back_history'], function () {

    Route::group(['as' => 'auth.', 'prefix' => 'auth'], function () {

        Route::get('/', [LoginController::class, 'create'])->name('login');
        Route::get('/logout', [LogoutController::class, 'logout'])->name('logout');



        Route::group(['middleware' => ['costum_guest']], function () {
            Route::post('/', [LoginController::class, 'store'])->name('login.store');


            Route::get('/forgot-password', function () {
                return view('modules.shared.auth.login');
            });

            Route::get('/reset-password', function () {
                return view('modules.shared.auth.login');
            });
        });
    });


    Route::get('/', [HomeController::class, 'default'])->name('home.default');

    Route::group(['middleware' => 'administrator_checker', 'prefix' => 'admin', 'as' => 'admin.'], function () {
        Route::get('/', [AdminController::class, 'index'])->name('index');

        Route::resource('structures', AdminStructureController::class);
        Route::group(['prefix' => 'structures', 'as' => 'structures.'], function () {
            Route::post('/{structure}/programs', [AdminStructureController::class, 'programs_add'])->name('programs.add');
            Route::delete('/{structure}/programs', [AdminStructureController::class, 'programs_remove'])->name('programs.remove');
        });

        Route::resource('structure-types', AdminStructureTypeController::class);
        Route::resource('units', AdminUnitController::class);
        Route::resource('indicators', AdminIndicatorController::class);

        Route::resource('programs', AdminProgramController::class);
        Route::group(['prefix' => 'programs', 'as' => 'programs.'], function () {
            Route::post('/{program}/structures', [AdminProgramController::class, 'members_add'])->name('members.add');
            Route::delete('/{program}/structures', [AdminProgramController::class, 'members_remove'])->name('members.remove');
        });
    });


    Route::group(['middleware' => 'collector_checker', 'prefix' => 'pf', 'as' => 'pf.'], function () {
        Route::get('/', [CollectorsProgramController::class, 'index'])->name('collectors.index');


        Route::group(['prefix' => '/{program}', 'as' => 'programs.'], function () {
            Route::resource('data', CollectorsDataController::class)->except(['show']);

            Route::get('/data/with-values', [CollectorsDataController::class, 'index_with_values'])->name('data.index.with.values');


            Route::group(['prefix' => '/data/{data}', 'as' => 'data.'], function () {
                Route::resource('records', CollectorsRecordController::class)->only(['index', 'create', 'store']);
            });
        });
    });
});

app/Models/Unit.php
<?php

namespace App\Models;

use App\Traits\Uuids;
use Illuminate\Database\Eloquent\Model;
use Sqits\UserStamps\Concerns\HasUserStamps;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Unit extends Model
{
    use HasFactory, HasUserStamps, SoftDeletes, Uuids;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'symbol',
        'name',
        'is_enable',
        'description',
    ];

    /**
     * Get all of the data for the Unit
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function data()
    {
        return $this->hasMany(Data::class, 'unit_id');
    }
}

app/Http/Controllers/Admin/UnitController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Interfaces\UnitRepositoryInterface;
use App\Http\Requests\UnitCreateOrUpdateRequest;

class UnitController extends Controller
{
    protected $unitRepository;
    /**
     * Class constructor.
     */
    public function __construct(UnitRepositoryInterface $unitRepository)
    {
        $this->unitRepository = $unitRepository;
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $units = $this->unitRepository->getList($request)['data'];

        return view("modules.admin.units.index")->with(compact('units'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $is_creation = true;
        return view('modules.admin.units.create-or-update')->with(compact('is_creation'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\UnitCreateOrUpdateRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UnitCreateOrUpdateRequest $request)
    {
        $is_creation = true;
        $rlts = $this->unitRepository->createOrUpdate($request);


        //dd(89, request()->all(), $rlts, ($rlts['error'] ? 'error' : 'success'));

        return redirect()->route('admin.units.create')->with(($rlts['error'] ? 'error' : 'success'), $rlts['message'])->with(compact('is_creation'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $is_creation = false;

        $rlts = $this->unitRepository->getById($id);

        if ($rlts['error']) {
            return redirect()->route('admin.units.index')->with('error', $rlts['message']);
        }

        $unit = $rlts['data'];

        // dd($unit, isset($unit));
        return view('modules.admin.units.create-or-update')->with(compact(['is_creation', 'unit']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UnitCreateOrUpdateRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UnitCreateOrUpdateRequest $request, $id)
    {
        $is_creation = false;
        $rlts = $this->unitRepository->createOrUpdate($request, $id);
        $unit = $rlts['data'];
        return redirect()->route('admin.units.edit', ['unit' => $id])->with(($rlts['error'] ? 'error' : 'success'), $rlts['message'])->with(compact(['is_creation', 'unit']));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/modules/admin/units/create-or-update.blade.php
@extends('base.base-with-header')

@section('title', $is_creation ? 'Creation d\'un unité' : 'Mise à jour d\'un unité')

@section('css')

    <!-- CSS-->
    <!-- Google Fonts -->
    <link rel="stylesheet" href="{{ asset('css/css.css') }}">
    <link rel="stylesheet" href="{{ asset('css/icon.css') }}">

    <!-- Bootstrap Core Css -->
    <link href="{{ asset('plugins/bootstrap/css/bootstrap.css') }}" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="{{ asset('plugins/node-waves/waves.css') }}" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="{{ asset('plugins/animate-css/animate.css') }}" rel="stylesheet" />

    <!-- JQuery DataTable Css -->
    <link href="{{ asset('plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css') }}" rel="stylesheet" />

    <!-- Custom Css -->
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">

    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link rel="stylesheet" href="{{ asset('css/themes/all-themes.css') }}">
    <style>
        .odd .dataTables_empty {
            text-align: center;
        }

        a[href="#next"] {
            background-color: #4CAF50 !important;
        }

        .wizard .steps .current a {
            background-color: #4CAF50 !important;
        }

        .pagination {
            display: flex !important;
        }

        .wizard .content {
            border: none !important;
        }

        .dataTables_paginate.paging_simple_numbers {
            display: flex !important;
            flex-direction: column !important;
            align-items: flex-end !important;
        }

        .table-responsive {
            overflow-x: unset !important;
        }

        .pagination li.active a {
            background-color: #3F51B5 !important;
            border-color: #3F51B5 !important;
        }


        .pagination li.active a:hover {
            background-color: #1F2B82 !important;
            border-color: #1F2B82 !important
        }


        .dataTables_empty {
            text-align: center !important;
        }

    </style>

@endsection


@section('content')
    @include('shared.menu.overlay')

    @include('shared.menu.search')

    @include('shared.menu.navbar')

    @include('shared.menu.default', ['activa' => 'units'])

    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <h2 class="pull-left">
                    UNITÉ
                    <small><u>Interface de gestion des unités</u></small>
                </h2>
                <ol class="breadcrumb pull-right">
                    <li><a href="#">Accueil</a></li>
                    <li><a href="{{ route('admin.units.index') }}">Unités</a></li>
                    <li class="active">
                        {{ $is_creation ? 'Creation' : 'Mise à jour' }}
                    </li>
                </ol>
            </div>

            <!-- Exportable Table -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                {{ $is_creation ? 'Creation d\'un unité' : 'Mise à jour d\'un unité' }}
                                @if (isset($unit) && !$is_creation)
                                    <span class="badge bg-blue">{{ $unit->name }}</span>
                                @endif
                            </h2>
                        </div>
                        <div class="body">

                            <form class="form-horizontal"
                                action="{{ $is_creation ? route('admin.units.store') : route('admin.units.update', ['unit' => $unit->id]) }}"
                                method="POST">
                                @csrf
                                @if (!$is_creation)
                                    @method("PUT")
                                @endif
                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                        <label for="create-or-update-unit-name">Nom <span
                                                class="col-red">*</span></label>
                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line">
                                                <input type="text" id="create-or-update-unit-name"
                                                    name="create_or_update_unit_name" class="form-control"
                                                    placeholder="Entrez le nom de l'unité"
                                                    value="{{ isset($unit) ? $unit->name : '' }}" required>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                        <label for="create-or-update-unit-symbol">Symbole <span
                                                class="col-red">*</span></label>
                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line">
                                                <input type="text" id="create-or-update-unit-symbol"
                                                    name="create_or_update_unit_symbol" class="form-control"
                                                    placeholder="Entrez le symbole associé à l'unité"
                                                    value="{{ isset($unit) ? $unit->symbol : '' }}" required>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="row clearfix">
                                    <div class="col-lg-2 col-md-2 col-sm-4 col-xs-5 form-control-label">
                                        <label for="create-or-update-unit-description">Description</label>
                                    </div>
                                    <div class="col-lg-10 col-md-10 col-sm-8 col-xs-7">
                                        <div class="form-group">
                                            <div class="form-line">
                                                <textarea rows="1" class="form-control no-resize auto-growth"
                                                    placeholder="Entrez la description de l'unité"
                                                    id="create-or-update-unit-description"
                                                    name="create_or_update_unit_description">{{ isset($unit) ? $unit->description : '' }}</textarea>

                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="row clearfix">
                                    <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-4 col-xs-offset-5">
                                        <input type="checkbox" id="create-or-update-unit-enable"
                                            name="create_or_update_unit_enable" class="filled-in chk-col-green"
                                            {{ $is_creation || (isset($unit) && $unit->is_enable == 1) ? 'checked' : '' }}>
                                        <label for="create-or-update-unit-enable">Activé</label>
                                    </div>
                                </div>
                                <div class="row clearfix">
                                    <div class="pull-right m-r--10">
                                        <button type="submit"
                                            class="btn btn-primary m-t-15 waves-effect">{{ $is_creation ? 'Enregistrer' : 'Mettre à jour' }}</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Exportable Table -->
        </div>
        </div>
    </section>

@endsection


@section('js')

    <!-- Select Plugin Js -->
    <script src="{{ asset('plugins/bootstrap-select/js/bootstrap-select.js') }}"></script>

    <!-- Slimscroll Plugin Js -->
    <script src="{{ asset('plugins/jquery-slimscroll/jquery.slimscroll.js') }}"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="{{ asset('plugins/node-waves/waves.js') }}"></script>

    <!-- Autosize Plugin Js -->
    <script src="{{ asset('plugins/autosize/autosize.js') }}"></script>

    <!-- Jquery DataTable Plugin Js -->
    <script src="{{ asset('plugins/jquery-datatable/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js') }}"></script>
    <script src="{{ asset('plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('plugins/jquery-datatable/extensions/export/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('plugins/jquery-datatable/extensions/export/jszip.min.js') }}"></script>
    <script src="{{ asset('plugins/jquery-datatable/extensions/export/pdfmake.min.js') }}"></script>
    <script src="{{ asset('plugins/jquery-datatable/extensions/export/vfs_fonts.js') }}"></script>
    <script src="{{ asset('plugins/jquery-datatable/extensions/export/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('plugins/jquery-datatable/extensions/export/buttons.print.min.js') }}"></script>

    <!-- Custom Js -->
    <script src="{{ asset('js/admin.js') }}"></script>
    <script src="{{ asset('js/pages/tables/jquery-datatable.js') }}"></script>

    <!-- Demo Js -->
    <script src="{{ asset('js/demo.js') }}"></script>
@endsection

resources/views/modules/admin/units/index.blade.php
@extends('base.base-with-header')

@section('title', 'Unités')

@section('css')

    <!-- CSS-->
    <!-- Google Fonts -->
    <link rel="stylesheet" href="{{ asset('css/css.css') }}">
    <link rel="stylesheet" href="{{ asset('css/icon.css') }}">

    <!-- Bootstrap Core Css -->
    <link href="{{ asset('plugins/bootstrap/css/bootstrap.css') }}" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="{{ asset('plugins/node-waves/waves.css') }}" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="{{ asset('plugins/animate-css/animate.css') }}" rel="stylesheet" />

    <!-- JQuery DataTable Css -->
    <link href="{{ asset('plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css') }}" rel="stylesheet" />

    <!-- Custom Css -->
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">

    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link rel="stylesheet" href="{{ asset('css/themes/all-themes.css') }}">
    <style>
        .odd .dataTables_empty {
            text-align: center;
        }

        a[href="#next"] {
            background-color: #4CAF50 !important;
        }

        .wizard .steps .current a {
            background-color: #4CAF50 !important;
        }

        .pagination {
            display: flex !important;
        }

        .wizard .content {
            border: none !important;
        }

        .dataTables_paginate.paging_simple_numbers {
            display: flex !important;
            flex-direction: column !important;
            align-items: flex-end !important;
        }

        .table-responsive {
            overflow-x: unset !important;
        }

        .pagination li.active a {
            background-color: #3F51B5 !important;
            border-color: #3F51B5 !important;
        }


        .pagination li.active a:hover {
            background-color: #1F2B82 !important;
            border-color: #1F2B82 !important
        }


        .dataTables_empty {
            text-align: center !important;
        }

    </style>

@endsection


@section('content')
    @include('shared.menu.overlay')

    @include('shared.menu.search')

    @include('shared.menu.navbar')

    @include('shared.menu.default', ['activa' => 'units'])

    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <h2 class="pull-left">
                    UNITÉ
                    <small><u>Interface de gestion des unités</u></small>
                </h2>
                {{ session('success') }}
                <ol class="breadcrumb pull-right">
                    <li><a href="#">Accueil</a></li>
                    <li class="active">Unité</li>
                </ol>
            </div>

            <!-- Exportable Table -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                Liste des unités
                            </h2>
                            <a href="{{ route('admin.units.create') }}"
                                class="btn bg-green btn-circle waves-effect waves-cyan waves-circle waves-float pull-right"
                                style="margin-bottom: 10px;">
                                <i class="material-icons">add</i>
                            </a>
                        </div>
                        <div class="body">
                            <div class="table-responsive">
                                <table class="table table-sm table-hover dataTable js-exportable">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Nom</th>
                                            <th>Symbole</th>
                                            <th>Nbr Donnée</th>
                                            <th>Status</th>
                                            <th class="align-center">Action</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>#</th>
                                            <th>Nom</th>
                                            <th>Symbole</th>
                                            <th>Nbr Donnée</th>
                                            <th>Status</th>
                                            <th class="align-center">Action</th>
                                        </tr>
                                    </tfoot>

                                    @php
                                        $counta = $units->count();
                                    @endphp

                                    <tbody>
                                        @foreach ($units->sortByDesc('created_at') as $unit)
                                            <tr>
                                                <td>{{ $counta }}</td>
                                                <td>{{ $unit->name }}</td>
                                                <td>{{ $unit->symbol }}</td>
                                                <td>{{ $unit->data->count() }}</td>
                                                <td> <span
                                                        class="{{ $unit->is_enable == 1 ? 'badge bg-green' : 'badge bg-red' }}">
                                                        {{ $unit->is_enable == 1 ? 'Activé' : 'Désactivé' }}
                                                    </span>
                                                </td>
                                                <td class="align-center">
                                                    <a class="btn btn-primary"
                                                        href="{{ route('admin.units.edit', ['unit' => $unit->id]) }}"><i
                                                            class="material-icons">visibility</i></a>
                                                    <button class="btn btn-danger unit-delete"><i
                                                            class="material-icons">delete</i></button>
                                                </td>
                                            </tr>

                                            @php
                                                $counta--;
                                            @endphp
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Exportable Table -->
        </div>
        </div>
    </section>
@endsection


@section('js')
    <!-- Jquery Core Js -->
    <script src="{{ asset('plugins/jquery/jquery.min.js') }}"></script>

    <!-- Bootstrap Core Js -->
    <script src="{{ asset('plugins/bootstrap/js/bootstrap.js') }}"></script>

    <!-- Select Plugin Js -->
    <script src="{{ asset('plugins/bootstrap-select/js/bootstrap-select.js') }}"></script>

    <!-- Slimscroll Plugin Js -->
    <script src="{{ asset('plugins/jquery-slimscroll/jquery.slimscroll.js') }}"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="{{ asset('plugins/node-waves/waves.js') }}"></script>

    <!-- Jquery DataTable Plugin Js -->
    <script src="{{ asset('plugins/jquery-datatable/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js') }}"></script>
    <script src="{{ asset('plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('plugins/jquery-datatable/extensions/export/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('plugins/jquery-datatable/extensions/export/jszip.min.js') }}"></script>
    <script src="{{ asset('plugins/jquery-datatable/extensions/export/pdfmake.min.js') }}"></script>
    <script src="{{ asset('plugins/jquery-datatable/extensions/export/vfs_fonts.js') }}"></script>
    <script src="{{ asset('plugins/jquery-datatable/extensions/export/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('plugins/jquery-datatable/extensions/export/buttons.print.min.js') }}"></script>

    <!-- Custom Js -->
    <script src="{{ asset('js/admin.js') }}"></script>
    <script src="{{ asset('js/pages/tables/jquery-datatable.js') }}"></script>

    <!-- Demo Js -->
    <script src="{{ asset('js/demo.js') }}"></script>
@endsection