routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\Admin\Controller as AdminController;
use App\Http\Controllers\Admin\UnitController as AdminUnitController;
use App\Http\Controllers\Admin\ProgramController as AdminProgramController;
use App\Http\Controllers\Admin\IndicatorController as AdminIndicatorController;
use App\Http\Controllers\Admin\StructureController as AdminStructureController;
use App\Http\Controllers\Collectors\DataController as CollectorsDataController;
use App\Http\Controllers\Collectors\RecordController as CollectorsRecordController;
use App\Http\Controllers\Collectors\ProgramController as CollectorsProgramController;
use App\Http\Controllers\Admin\StructureTypeController as AdminStructureTypeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'revalidate_back_history'], function () {

    Route::group(['as' => 'auth.', 'prefix' => 'auth'], function () {

        Route::get('/', [LoginController::class, 'create'])->name('login');
        Route::get('/logout', [LogoutController::class, 'logout'])->name('logout');



        Route::group(['middleware' => ['costum_guest']], function () {
            Route::post('/', [LoginController::class, 'store'])->name('login.store');


            Route::get('/forgot-password', function () {
                return view('modules.shared.auth.login');
            });

            Route::get('/reset-password', function () {
                return view('modules.shared.auth.login');
            });
        });
    });


    Route::get('/', [HomeController::class, 'default'])->name('home.default');

    Route::group(['middleware' => 'administrator_checker', 'prefix' => 'admin', 'as' => 'admin.'], function () {
        Route::get('/', [AdminController::class, 'index'])->name('index');

        Route::resource('structures', AdminStructureController::class);
        Route::group(['prefix' => 'structures', 'as' => 'structures.'], function () {
            Route::post('/{structure}/programs', [AdminStructureController::class, 'programs_add'])->name('programs.add');
            Route::delete('/{structure}/programs', [AdminStructureController::class, 'programs_remove'])->name('programs.remove');
        });

        Route::resource('structure-types', AdminStructureTypeController::class);
        Route::resource('units', AdminUnitController::class);
        Route::resource('indicators', AdminIndicatorController::class);

        Route::resource('programs', AdminProgramController::class);
        Route::group(['prefix' => 'programs', 'as' => 'programs.'], function () {
            Route::post('/{program}/structures', [AdminProgramController::class, 'members_add'])->name('members.add');
            Route::delete('/{program}/structures', [AdminProgramController::class, 'members_remove'])->name('members.remove');
        });
    });


    Route::group(['middleware' => 'collector_checker', 'prefix' => 'pf', 'as' => 'pf.'], function () {
        Route::get('/', [CollectorsProgramController::class, 'index'])->name('collectors.index');


        Route::group(['prefix' => '/{program}', 'as' => 'programs.'], function () {
            Route::resource('data', CollectorsDataController::class)->except(['show']);

            Route::get('/data/with-values', [CollectorsDataController::class, 'index_with_values'])->name('data.index.with.values');


            Route::group(['prefix' => '/data/{data}', 'as' => 'data.'], function () {
                Route::resource('records', CollectorsRecordController::class)->only(['index', 'create', 'store']);
            });
        });
    });
});

app/Models/Data.php
<?php

namespace App\Models;

use App\Traits\Uuids;
use Illuminate\Database\Eloquent\Model;
use Sqits\UserStamps\Concerns\HasUserStamps;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Data extends Model
{
    use HasFactory, HasUserStamps, SoftDeletes, Uuids;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = "data";

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'is_enable',
        'description',
        'collect_method',
        'source',
        'unit_id',
        'indicator_id',
        'program_id',
        'visibility',
        'responsible_structure_id'
    ];

    /**
     * Get the unit that owns the Data
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function unit()
    {
        return $this->belongsTo(Unit::class, 'unit_id');
    }



    /**
     * Get the indicator that owns the Data
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function indicator()
    {
        return $this->belongsTo(Indicator::class, 'indicator_id');
    }


    /**
     * Get the responsible_structure that owns the Data
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function responsible_structure()
    {
        return $this->belongsTo(Structure::class, 'responsible_structure_id');
    }

    /**
     * Get all of the records for the Data
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function records(): HasMany
    {
        return $this->hasMany(Record::class, 'data_id', 'id');
    }

    /**
     * Get the program that owns the Data
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function program(): BelongsTo
    {
        return $this->belongsTo(Program::class, 'program_id');
    }
}

app/Http/Controllers/Collectors/DataController.php
<?php

namespace App\Http\Controllers\Collectors;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Interfaces\DataRepositoryInterface;
use App\Interfaces\UnitRepositoryInterface;
use App\Interfaces\ProgramRepositoryInterface;
use App\Http\Requests\DataCreateOrUpdateRequest;
use App\Interfaces\IndicatorRepositoryInterface;
use App\Interfaces\StructureRepositoryInterface;

class DataController extends Controller
{
    protected $programRepository;
    protected $dataRepository;
    protected $unitRepository;
    protected $structureRepository;
    protected $indicatorRepository;

    /**
     * Class constructor.
     */
    public function __construct(ProgramRepositoryInterface $programRepository, DataRepositoryInterface $dataRepository, UnitRepositoryInterface $unitRepository, StructureRepositoryInterface $structureRepository, IndicatorRepositoryInterface $indicatorRepository)
    {
        $this->programRepository = $programRepository;
        $this->dataRepository = $dataRepository;
        $this->unitRepository = $unitRepository;
        $this->structureRepository = $structureRepository;
        $this->indicatorRepository = $indicatorRepository;
    }
    /**
     * Display a listing of the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function index(Request  $request, $id)
    {
        $program = $this->programRepository->getById($id)['data'];
        return view('modules.collectors.data.index')->with(compact(['program']));
    }


    /**
     * Display a listing of the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function index_with_values(Request  $request, $id)
    {
        $program = $this->programRepository->getById($id)['data'];
        return view('modules.collectors.data.index-values')->with(compact(['program']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  uuid  $program
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request, $program)
    {
        $is_creation = true;
        $program = $this->programRepository->getById($program)['data'];
        $units = $this->unitRepository->getList($request)['data'];
        $structures = $this->structureRepository->getList($request)['data'];
        $indicators = $this->indicatorRepository->getList($request)['data'];

        return view('modules.collectors.data.create-or-update')->with(compact(['is_creation', 'program', 'units', 'structures', 'indicators']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\DataCreateOrUpdateRequest  $request
     * @param  uuid  $program
     * @return \Illuminate\Http\Response
     */
    public function store(DataCreateOrUpdateRequest $request, $program)
    {
        $is_creation = true;
        $rlts = $this->dataRepository->createOrUpdate($request, $program);

        return redirect()->route('pf.programs.data.create', ['program' => $program])->with(($rlts['error'] ? 'error' : 'success'), $rlts['message'])->with(compact('is_creation'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $program
     * @param  int  $data
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $program, $data)
    {
        $is_creation = false;

        $rlts = $this->programRepository->getById($program);

        if ($rlts['error']) {
            return redirect()->route('admin.programs.index')->with('error', $rlts['message']);
        }
        $program = $rlts['data'];



        $rlts = $this->dataRepository->getById($data);

        if ($rlts['error']) {
            return redirect()->route('admin.programs.index')->with('error', $rlts['message']);
        }

        $data = $rlts['data'];
        $units = $this->unitRepository->getList($request)['data'];
        $structures = $this->structureRepository->getList($request)['data'];
        $indicators = $this->indicatorRepository->getList($request)['data'];

        // dd($program, isset($program));
        return view('modules.collectors.data.create-or-update')->with(compact(['is_creation', 'program', 'units', 'structures', 'indicators', 'data']));
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\DataCreateOrUpdateRequest  $request
     * @param  uuid  $program
     * @param  uuid  $data
     * @return \Illuminate\Http\Response
     */
    public function update(DataCreateOrUpdateRequest $request, $program, $data)
    {
        $rlts = $this->dataRepository->createOrUpdate($request, $program, $data);
        return redirect()->route('pf.programs.data.edit', ['program' => $program, 'data' => $data])->with(($rlts['error'] ? 'error' : 'success'), $rlts['message']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Collectors/ProgramController.php
<?php

namespace App\Http\Controllers\Collectors;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Interfaces\ProgramRepositoryInterface;

class ProgramController extends Controller
{


    protected $programRepository;

    /**
     * Class constructor.
     */
    public function __construct(ProgramRepositoryInterface $programRepository)
    {
        $this->programRepository = $programRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $programs = $this->programRepository->getList($request)['data'];
        return view('modules.collectors.index')->with(compact('programs'));
    }
}

app/Http/Controllers/Collectors/RecordController.php
<?php

namespace App\Http\Controllers\Collectors;

use App\Models\Data;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\RecordCreateOrUpdateRequest;
use App\Interfaces\DataRepositoryInterface;
use App\Interfaces\UnitRepositoryInterface;
use App\Interfaces\RecordRepositoryInterface;
use App\Interfaces\ProgramRepositoryInterface;
use App\Interfaces\IndicatorRepositoryInterface;
use App\Interfaces\StructureRepositoryInterface;

class RecordController extends Controller
{
    protected $programRepository;
    protected $dataRepository;
    protected $unitRepository;
    protected $structureRepository;
    protected $indicatorRepository;
    protected $recordRepository;

    /**
     * Class constructor.
     */
    public function __construct(
        ProgramRepositoryInterface $programRepository,
        DataRepositoryInterface $dataRepository,
        UnitRepositoryInterface $unitRepository,
        StructureRepositoryInterface $structureRepository,
        IndicatorRepositoryInterface $indicatorRepository,
        RecordRepositoryInterface $recordRepository
    ) {
        $this->programRepository = $programRepository;
        $this->dataRepository = $dataRepository;
        $this->unitRepository = $unitRepository;
        $this->structureRepository = $structureRepository;
        $this->indicatorRepository = $indicatorRepository;
        $this->recordRepository = $recordRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  uuid  $program
     * @param  uuid  $data
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request, $program, $data)
    {
        $is_creation = true;
        $data = $this->dataRepository->getById($data)['data'];
        //dd($data->records->sortByDesc('trimestre_number')->toArray(), $data->records->sortBy('trimestre_number')->values()->toArray());
        return view('modules.collectors.data.records.create-or-update')->with(compact(["data"]));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\RecordCreateOrUpdateRequest  $request
     * @param  uuid  $program
     * @param  uuid  $data
     * @return \Illuminate\Http\Response
     */
    public function store(RecordCreateOrUpdateRequest $request, $program, $data)
    {
        //dd($request->all());
        $rlts = $this->recordRepository->createOrUpdate($request, $data);

        return redirect()->route('pf.programs.data.records.create', ['program' => $program, "data" => $data])->with(($rlts['error'] ? 'error' : 'success'), $rlts['message']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/modules/collectors/data/index-values.blade.php
@extends('base.base-without-header')

@section('title', 'Point focal - Liste des données dans Programme 01')

@section('css')

    <!-- CSS-->
    <!-- Google Fonts -->
    <link rel="stylesheet" href="{{ asset('css/css.css') }}">
    <link rel="stylesheet" href="{{ asset('css/icon.css') }}">

    <!-- Bootstrap Core Css -->
    <link rel="stylesheet" href="{{ asset('plugins/bootstrap/css/bootstrap.css') }}">

    <!-- Bootstrap Select Css -->
    <link href="{{ asset('plugins/bootstrap-select/css/bootstrap-select.css') }}" rel="stylesheet" />

    <!-- Waves Effect Css -->
    <link rel="stylesheet" href="{{ asset('plugins/node-waves/waves.css') }}">
    <!-- Waves Effect Css -->
    <link rel="stylesheet" href="{{ asset('plugins/jquery-toast/dist/jquery.toast.min.css') }}">

    <!-- Animation Css -->
    <link rel="stylesheet" href="{{ asset('plugins/animate-css/animate.css') }}">


    <!-- Bootstrap Material Datetime Picker Css -->
    <link href="{{ asset('plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css') }}"
        rel="stylesheet" />

    <!-- JQuery DataTable Css -->
    <link rel="stylesheet" href="{{ asset('plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css') }}">

    <!-- Custom Css -->
    <link rel="stylesheet" href="{{ asset('css/style.css') }}">

    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link rel="stylesheet" href="{{ asset('css/themes/all-themes.css') }}">
    <style>
        .odd .dataTables_empty {
            text-align: center;
        }

        a[href="#next"] {
            background-color: #4CAF50 !important;
        }

        .wizard .steps .current a {
            background-color: #4CAF50 !important;
        }

        .pagination {
            display: flex !important;
        }

        .wizard .content {
            border: none !important;
        }

        .dataTables_paginate.paging_simple_numbers {
            display: flex !important;
            flex-direction: column !important;
            align-items: flex-end !important;
        }

        .table-responsive {
            overflow-x: unset !important;
        }

        .pagination li.active a {
            background-color: #3F51B5 !important;
            border-color: #3F51B5 !important;
        }


        .pagination li.active a:hover {
            background-color: #1F2B82 !important;
            border-color: #1F2B82 !important
        }


        .dataTables_empty {
            text-align: center !important;
        }

        #dropdownMenu1 {
            box-shadow: none !important;
        }

    </style>
@endsection

@section('content')
    @php
    $current_structure_is_inter = auth()->user()->structure ? $program->structures->contains('id', auth()->user()->structure->id) : false;
    @endphp
    <div class="container">

        <div class="card" style="height: 100% !important; border: none !important; box-shadow: none !important;">
            <div class="header">
                {{-- <h2 class="pull-left"> --}}
                <h2 style="display: inline-block !important">
                    Programme: <strong class="col-green">{{ $program->name }}</strong>
                    @if ($current_structure_is_inter)
                        <a href="{{ route('pf.programs.data.create', ['program' => $program->id]) }}"
                            class="btn bg-green btn-xs waves-effect p-l-5"><i class="material-icons"
                                style="font-size: 15px !important">add</i>Nouvelle donnée</a>
                    @endif
                    <a class="btn btn-xs bg-blue"
                        href="{{ route('pf.programs.data.index', ['program' => $program->id]) }}"><i
                            class="material-icons">view_list</i> Liste sans valeurs</a>

                    <small> Liste des structures intervenant :
                        @foreach ($program->structures as $structure)
                            <span class="badge">{{ $structure->name }}</span>
                        @endforeach
                    </small>
                </h2>

                <a href="{{ route('pf.collectors.index') }}" class="btn bg-red btn-xs waves-effect pull-right">
                    <i class="material-icons">keyboard_backspace</i>
                    <span>Retour</span>
                </a>
            </div>

            <div class="body">

                <div class="table-responsive">
                    <table class="table table-hover dataTable js-exportable">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Désignation</th>
                                <th>Année</th>
                                <th>Nbr trimestre</th>
                                <th>Valeur</th>
                                <th>Unité</th>
                                <th>Indicateur</th>
                                <th>Structure Responsable</th>
                                <th>source</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>#</th>
                                <th>Désignation</th>
                                <th>Année</th>
                                <th>Nbr trimestre</th>
                                <th>Valeur</th>
                                <th>Unité</th>
                                <th>Indicateur</th>
                                <th>Structure Responsable</th>
                                <th>Action</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            @php
                                $counta = $program->records->count();
                            @endphp

                            @foreach ($program->records->sortByDesc('created_at') as $record)

                                <tr>
                                    <td>{{ $counta }}</td>

                                    <td> {{ $record->data->name }}</td>

                                    <td> {{ $record->year }}</td>

                                    <td> {{ $record->trimestre_number }}</td>

                                    <td> {{ $record->value }}</td>

                                    <td data-toggle="tooltip" data-placement="top" title=""
                                        data-original-title="{{ $record->data->unit->name }}">
                                        {{ $record->data->unit->symbol }}</td>

                                    <td><span
                                            class="badge">{{ $record->data->indicator ? $record->data->indicator->name : '' }}</span>
                                    </td>

                                    <td>{{ 'Structure 1' }}</td>

                                    <td>
                                        <span class="badge {{ $record->data->source ? 'bg-blue' : 'bg-red' }}"
                                            data-toggle="{{ $record->data->source ? 'tooltip' : '' }}"
                                            data-placement="top" title=""
                                            data-original-title="{{ $record->data->source }}">
                                            {{ $record->data->source ? 'FOURNIS' : 'NON-FOURNIS' }}</span>
                                    </td>

                                    <td class="text-nowrap text-center">
                                        @if ($current_structure_is_inter)
                                            <a class="btn btn-xs btn-success"
                                                href="{{ route('pf.programs.data.edit', ['program' => $program->id, 'data' => $record->data->id]) }}"><i
                                                    class="material-icons">edit</i></a>
                                            <a class="btn btn-xs bg-indigo"
                                                href="{{ route('pf.programs.data.records.create', ['program' => $program->id, 'data' => $record->data->id]) }}"><i
                                                    class="material-icons">send</i></a>
                                        @else
                                            -
                                        @endif
                                    </td>
                                </tr>
                                @php
                                    $counta--;
                                @endphp
                            @endforeach
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
@endsection

@section('js')

    <!-- Jquery Core Js -->
    <script src="{{ asset('plugins/jquery/jquery.min.js') }}"></script>

    <!-- Bootstrap Core Js -->
    <script src="{{ asset('plugins/bootstrap/js/bootstrap.js') }}"></script>

    <!-- Jequry Taost Js -->
    <script src="{{ asset('plugins/jquery-toast/dist/jquery.toast.min.js') }}"></script>

    <!-- Select Plugin Js -->
    <script src="{{ asset('plugins/bootstrap-select/js/bootstrap-select.js') }}"></script>

    <!-- Slimscroll Plugin Js -->
    <script src="{{ asset('plugins/jquery-slimscroll/jquery.slimscroll.js') }}"></script>

    <!-- Multi Select Plugin Js -->
    <script src="{{ asset('plugins/multi-select/js/jquery.multi-select.js') }}"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="{{ asset('plugins/node-waves/waves.js') }}"></script>

    <!-- Jquery DataTable Plugin Js -->
    <script src="{{ asset('plugins/jquery-datatable/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js') }}"></script>
    <script src="{{ asset('plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('plugins/jquery-datatable/extensions/export/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('plugins/jquery-datatable/extensions/export/jszip.min.js') }}"></script>
    <script src="{{ asset('plugins/jquery-datatable/extensions/export/pdfmake.min.js') }}"></script>
    <script src="{{ asset('plugins/jquery-datatable/extensions/export/vfs_fonts.js') }}"></script>
    <script src="{{ asset('plugins/jquery-datatable/extensions/export/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('plugins/jquery-datatable/extensions/export/buttons.print.min.js') }}"></script>

    <!-- Moment Plugin Js -->
    <script src="{{ asset('plugins/momentjs/moment-with-locales.min.js') }}"></script>

    <!-- Bootstrap Material Datetime Picker Plugin Js -->
    <script src="{{ asset('plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js') }}">
    </script>

    <!-- JQuery Steps Plugin Js -->
    <script src="{{ asset('plugins/jquery-steps/jquery.steps.js') }}"></script>

    <!-- Custom Js -->
    <script src="{{ asset('js/admin.js') }}"></script>


    <!-- Jquery Validation Plugin Css -->
    <script src="{{ asset('plugins/jquery-validation/jquery.validate.js') }}"></script>

    <script src="{{ asset('js/pages/forms/form-wizard.js') }}"></script>
    <script src="{{ asset('js/pages/tables/jquery-datatable-c.js') }}"></script>

    <!-- Demo Js -->
    <script src="{{ asset('js/demo.js') }}"></script>

    <script>
        @if (session('success'))
            $.toast({
            heading: 'Succès',
            text: "{{ session('success') }}",
            hideAfter: 10000,
            position: 'bottom-right',
            showHideTransition: 'slide',
            bgColor: "#4CAF50",
            icon: 'success'
            })
        @endif

        @if (session('error'))
            $.toast({
            heading: 'Erreur',
            text: "{{ session('error') }}",
            hideAfter: 10000,
            position: 'bottom-right',
            showHideTransition: 'slide',
            icon: 'error'
            })
        @endif

        @if (session('warning'))
            $.toast({
            heading: 'Attention',
            text: "{{ session('warning') }}",
            hideAfter: 10000,
            position: 'bottom-right',
            showHideTransition: 'slide',
            icon: 'warning'
            })
        @endif


        $(function() {
            //Tooltip
            $('[data-toggle="tooltip"]').tooltip({
                container: 'body'
            });
        })
    </script>

@endsection