routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\Admin\Controller as AdminController;
use App\Http\Controllers\Admin\UnitController as AdminUnitController;
use App\Http\Controllers\Admin\ProgramController as AdminProgramController;
use App\Http\Controllers\Admin\IndicatorController as AdminIndicatorController;
use App\Http\Controllers\Admin\StructureController as AdminStructureController;
use App\Http\Controllers\Collectors\DataController as CollectorsDataController;
use App\Http\Controllers\Collectors\RecordController as CollectorsRecordController;
use App\Http\Controllers\Collectors\ProgramController as CollectorsProgramController;
use App\Http\Controllers\Admin\StructureTypeController as AdminStructureTypeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'revalidate_back_history'], function () {

    Route::group(['as' => 'auth.', 'prefix' => 'auth'], function () {

        Route::get('/', [LoginController::class, 'create'])->name('login');
        Route::get('/logout', [LogoutController::class, 'logout'])->name('logout');



        Route::group(['middleware' => ['costum_guest']], function () {
            Route::post('/', [LoginController::class, 'store'])->name('login.store');


            Route::get('/forgot-password', function () {
                return view('modules.shared.auth.login');
            });

            Route::get('/reset-password', function () {
                return view('modules.shared.auth.login');
            });
        });
    });


    Route::get('/', [HomeController::class, 'default'])->name('home.default');

    Route::group(['middleware' => 'administrator_checker', 'prefix' => 'admin', 'as' => 'admin.'], function () {
        Route::get('/', [AdminController::class, 'index'])->name('index');

        Route::resource('structures', AdminStructureController::class);
        Route::group(['prefix' => 'structures', 'as' => 'structures.'], function () {
            Route::post('/{structure}/programs', [AdminStructureController::class, 'programs_add'])->name('programs.add');
            Route::delete('/{structure}/programs', [AdminStructureController::class, 'programs_remove'])->name('programs.remove');
        });

        Route::resource('structure-types', AdminStructureTypeController::class);
        Route::resource('units', AdminUnitController::class);
        Route::resource('indicators', AdminIndicatorController::class);

        Route::resource('programs', AdminProgramController::class);
        Route::group(['prefix' => 'programs', 'as' => 'programs.'], function () {
            Route::post('/{program}/structures', [AdminProgramController::class, 'members_add'])->name('members.add');
            Route::delete('/{program}/structures', [AdminProgramController::class, 'members_remove'])->name('members.remove');
        });
    });


    Route::group(['middleware' => 'collector_checker', 'prefix' => 'pf', 'as' => 'pf.'], function () {
        Route::get('/', [CollectorsProgramController::class, 'index'])->name('collectors.index');


        Route::group(['prefix' => '/{program}', 'as' => 'programs.'], function () {
            Route::resource('data', CollectorsDataController::class)->except(['show']);

            Route::get('/data/with-values', [CollectorsDataController::class, 'index_with_values'])->name('data.index.with.values');


            Route::group(['prefix' => '/data/{data}', 'as' => 'data.'], function () {
                Route::resource('records', CollectorsRecordController::class)->only(['index', 'create', 'store']);
            });
        });
    });
});

resources/views/modules/admin/index.blade.php
@extends('base.base-with-header')

@section('title', 'Accueil')

@section('css')

    <!-- CSS-->
    <!-- Google Fonts -->
    <link rel="stylesheet" href="{{ asset('css/css.css') }}">
    <link rel="stylesheet" href="{{ asset('css/icon.css') }}">

    <!-- Bootstrap Core Css -->
    <link href="{{ asset('plugins/bootstrap/css/bootstrap.css') }}" rel="stylesheet">

    <!-- Waves Effect Css -->
    <link href="{{ asset('plugins/node-waves/waves.css') }}" rel="stylesheet" />

    <!-- Animation Css -->
    <link href="{{ asset('plugins/animate-css/animate.css') }}" rel="stylesheet" />

    <!-- Morris Chart Css-->
    <link href="{{ asset('plugins/morrisjs/morris.css') }}" rel="stylesheet" />

    <!-- JQuery DataTable Css -->
    <link rel="stylesheet" href="{{ asset('plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css') }}">

    <!-- Custom Css -->
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">

    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link rel="stylesheet" href="{{ asset('css/themes/all-themes.css') }}">

    <style>
        .dataTables_empty {
            text-align: center !important;
        }

    </style>

@endsection


@section('content')
    @include('shared.menu.overlay')

    @include('shared.menu.search')

    @include('shared.menu.navbar')

    @include('shared.menu.default', ['activa' => 'home'])

    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <h2>DASHBOARD</h2>
            </div>

            <!-- Widgets -->
            <div class="row clearfix">
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <div class="info-box bg-pink hover-expand-effect">
                        <div class="icon">
                            <i class="material-icons">business</i>
                        </div>
                        <div class="content">
                            <div class="text">STRUCTURES</div>
                            <div class="number count-to" data-from="0" data-to="{{ $c_structure }}" data-speed="15"
                                data-fresh-interval="2"></div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <div class="info-box bg-cyan hover-expand-effect">
                        <div class="icon">
                            <i class="material-icons">assignment</i>
                        </div>
                        <div class="content">
                            <div class="text">PROGRAMMES</div>
                            <div class="number count-to" data-from="0" data-to="{{ $c_program }}" data-speed="1000"
                                data-fresh-interval="2"></div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <div class="info-box bg-light-green hover-expand-effect">
                        <div class="icon">
                            <i class="material-icons">label</i>
                        </div>
                        <div class="content">
                            <div class="text">UNITES</div>
                            <div class="number count-to" data-from="0" data-to="{{ $c_unit }}" data-speed="1000"
                                data-fresh-interval="2"></div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                    <div class="info-box bg-orange hover-expand-effect">
                        <div class="icon">
                            <i class="material-icons">grain</i>
                        </div>
                        <div class="content">
                            <div class="text">DONNEES</div>
                            <div class="number count-to" data-from="0" data-to="{{ $c_data }}" data-speed="1000"
                                data-fresh-interval="2"></div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Widgets -->
            <div class="row clearfix">
                <!-- Task Info -->
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                    <div class="card">
                        <div class="header">
                            <h2>LISTE DES PROGRAMMES</h2>
                            <ul class="header-dropdown m-r--5">
                                <li class="dropdown">
                                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"
                                        role="button" aria-haspopup="true" aria-expanded="false">
                                        <i class="material-icons">more_vert</i>
                                    </a>
                                    <ul class="dropdown-menu pull-right">
                                        <li><a href="javascript:void(0);">Action</a></li>
                                        <li><a href="javascript:void(0);">Another action</a></li>
                                        <li><a href="javascript:void(0);">Something else here</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>

                        <div class="body">
                            <div class="table-responsive">
                                <table class="table table-sm table-hover dataTable js-exportable">
                                    <thead>
                                        <tr>
                                            <th class="export">#</th>
                                            <th class="export">Nom</th>
                                            <th class="export">Nbr Donnée</th>
                                            <th class="export">Status</th>
                                            <th class="align-center">Action</th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>#</th>
                                            <th>Nom</th>
                                            <th>Nbr Donnée</th>
                                            <th>Status</th>
                                            <th class="align-center">Action</th>
                                        </tr>
                                    </tfoot>

                                    @php
                                        $counta = $programs->count();
                                    @endphp

                                    <tbody>
                                        @foreach ($programs->sortByDesc('created_at') as $program)
                                            <tr>
                                                <td>{{ $counta }}</td>
                                                <td>
                                                    <span data-toggle="tooltip" data-placement="top" title=""
                                                        data-original-title="{{ $program->objective }}">{{ $program->name }}</span>
                                                </td>
                                                <td>{{ $program->structures->count() }}</td>
                                                <td> <span
                                                        class="{{ $program->is_enable == 1 ? 'badge bg-green' : 'badge bg-red' }}">
                                                        {{ $program->is_enable == 1 ? 'ACTIVE' : 'DESACTIVE' }}
                                                    </span>
                                                </td>
                                                <td class="align-center">
                                                    <a class="btn btn-primary"
                                                        href="{{ route('admin.programs.edit', ['program' => $program->id]) }}"><i
                                                            class="material-icons">visibility</i></a>
                                                </td>
                                            </tr>

                                            @php
                                                $counta--;
                                            @endphp
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- #END# Task Info -->
            </div>
        </div>
    </section>
@endsection


@section('js')
    <!-- Jquery Core Js -->
    <script src="{{ asset('plugins/jquery/jquery.min.js') }}"></script>

    <!-- Bootstrap Core Js -->
    <script src="{{ asset('plugins/bootstrap/js/bootstrap.js') }}"></script>

    <!-- Select Plugin Js -->
    <script src="{{ asset('plugins/bootstrap-select/js/bootstrap-select.js') }}"></script>

    <!-- Slimscroll Plugin Js -->
    <script src="{{ asset('plugins/jquery-slimscroll/jquery.slimscroll.js') }}"></script>

    <!-- Waves Effect Plugin Js -->
    <script src="{{ asset('plugins/node-waves/waves.js') }}"></script>



    <!-- Jquery DataTable Plugin Js -->
    <script src="{{ asset('plugins/jquery-datatable/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js') }}"></script>
    <script src="{{ asset('plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('plugins/jquery-datatable/extensions/export/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('plugins/jquery-datatable/extensions/export/jszip.min.js') }}"></script>
    <script src="{{ asset('plugins/jquery-datatable/extensions/export/pdfmake.min.js') }}"></script>
    <script src="{{ asset('plugins/jquery-datatable/extensions/export/vfs_fonts.js') }}"></script>
    <script src="{{ asset('plugins/jquery-datatable/extensions/export/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('plugins/jquery-datatable/extensions/export/buttons.print.min.js') }}"></script>

    <!-- Jquery CountTo Plugin Js -->
    <script src="{{ asset('plugins/jquery-countto/jquery.countTo.js') }}"></script>

    <!-- Morris Plugin Js -->
    <script src="{{ asset('plugins/raphael/raphael.min.js') }}"></script>
    <script src="{{ asset('plugins/morrisjs/morris.js') }}"></script>

    <!-- ChartJs -->
    <script src="{{ asset('plugins/chartjs/Chart.bundle.js') }}"></script>

    <!-- Flot Charts Plugin Js -->
    <script src="{{ asset('plugins/flot-charts/jquery.flot.js') }}"></script>
    <script src="{{ asset('plugins/flot-charts/jquery.flot.resize.js') }}"></script>
    <script src="{{ asset('plugins/flot-charts/jquery.flot.pie.js') }}"></script>
    <script src="{{ asset('plugins/flot-charts/jquery.flot.categories.js') }}"></script>
    <script src="{{ asset('plugins/flot-charts/jquery.flot.time.js') }}"></script>

    <!-- Sparkline Chart Plugin Js -->
    <script src="{{ asset('plugins/jquery-sparkline/jquery.sparkline.js') }}"></script>

    <script src="{{ asset('js/pages/tables/jquery-datatable-c.js') }}"></script>

    <!-- Custom Js -->
    <script src="{{ asset('js/admin.js') }}"></script>
    <script src="{{ asset('js/pages/index.js') }}"></script>

    <!-- Demo Js -->
    <script src="{{ asset('js/demo.js') }}"></script>

    <script>
        $(function() {
            //Tooltip
            $('[data-toggle="tooltip"]').tooltip({
                container: 'body'
            });
        })
    </script>
@endsection